version: 2

project_name: p2r

builds:
  - id: p2r
    main: ./cmd/p2r
    binary: p2r
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/xuanli520/p2r_tui/cmd.version={{.Version}} -X github.com/xuanli520/p2r_tui/cmd.commit={{.ShortCommit}} -X github.com/xuanli520/p2r_tui/cmd.buildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
