package workflowadapter

import (
	"fmt"

	"github.com/purplevoid/harbor-factory/pkg/workflowkit"
)

const (
	// StandardAuthoringWorkflowTemplateID and Version identify the closed
	// pre-materialization workflow. Its subject is an immutable
	// AuthoringSession/source snapshot, not an empty TaskRevision. The final
	// materialize_task stage atomically creates the first task revision and
	// emits an explicit handoff for a separate task-bound CodeEdge Phase-1 Run.
	StandardAuthoringWorkflowTemplateID      = "harbor.standard-authoring"
	StandardAuthoringWorkflowTemplateVersion = "1.2.0"

	// StandardAuthoringTaskAdmissionTemplateVersion is reserved for the
	// additive Authoring contract release. Keeping it distinct from 1.2.0
	// prevents a new production binary from reinterpreting a frozen legacy Run.
	StandardAuthoringTaskAdmissionTemplateVersion = "1.3.0"

	// StandardAuthoringBriefTemplateVersion adds the immutable authoring_brief
	// input while preserving the exact 1.2.0 and 1.3.0 templates for historical
	// parsing and recovery.
	StandardAuthoringBriefTemplateVersion = "1.4.0"

	// StandardAuthoringRepairFeedbackTemplateVersion adds optional, durable and
	// immutable downstream review and admission artifacts to the stages that may be
	// regenerated by a repair continuation. The 1.4.0 brief template remains
	// registered unchanged for historical Run parsing and recovery.
	StandardAuthoringRepairFeedbackTemplateVersion = "1.5.0"

	// StandardAuthoringTestsAnalysisInputTemplateVersion binds generators to the
	// current reviewed Dockerfile and orders tests_analysis after test_generate so
	// repair feedback can be evaluated against the regenerated test script. The
	// 1.5.0 repair-feedback template remains registered unchanged for historical
	// Run parsing.
	StandardAuthoringTestsAnalysisInputTemplateVersion = "1.6.0"

	// StandardAuthoringHarnessTemplateVersion adds two bounded ReAct validation
	// stages. dockerfile_build_validate produces the exact Dockerfile reviewed by
	// content_review, while authoring_harness repairs and proves the final solve
	// and test scripts with initial-fail plus oracle-pass execution. The 1.6.0
	// template remains registered unchanged for historical Run parsing.
	StandardAuthoringHarnessTemplateVersion = "1.7.0"

	// StandardAuthoringFixedFileTemplateVersion preserves the 1.7.0 DAG and
	// Docker ReAct evidence contract, while changing only solve_generate and
	// test_generate's artifact handoff: each script is host-read from an
	// attempt-scoped fixed workspace file after a pass-only receipt. Keeping it
	// separate prevents a new executor from reinterpreting frozen 1.7.0 base64
	// turn programs.
	StandardAuthoringFixedFileTemplateVersion = "1.8.0"

	standardAuthoringCatalogID      = "harbor.standard-authoring-stage-catalog"
	standardAuthoringCatalogVersion = "1.2.0"

	// StandardAuthoringTaskDesignMaxTurns bounds the task-design Codex
	// conversation in this source-session template. It intentionally does not
	// alter the task-bound Standard catalog, whose task_design stage remains a
	// separate workflow contract.
	StandardAuthoringTaskDesignMaxTurns = 30

	// StandardAuthoringTaskHandoffArtifact is emitted only by materialize_task.
	// It is a receipt for a newly sealed task revision, not a mutable workspace
	// path and not an authorization to continue task-bound work in the source
	// AuthoringSession Run.
	StandardAuthoringTaskHandoffArtifact               = "authoring_task_handoff"
	StandardAuthoringTaskHandoffSchemaVersion          = "harbor.authoring-task-handoff.v1"
	StandardAuthoringTaskAdmissionHandoffSchemaVersion = "harbor.authoring-task-handoff.v2"

	StandardAuthoringValidatedDockerfileArtifact        = "validated_dockerfile"
	StandardAuthoringDockerfileBuildReportArtifact      = "dockerfile_build_report"
	StandardAuthoringDockerfileBuildReportSchemaVersion = "harbor.standard-authoring-dockerfile-build-report.v1"
	StandardAuthoringValidatedSolveScriptArtifact       = "validated_solve_script"
	StandardAuthoringValidatedTestScriptArtifact        = "validated_test_script"
	StandardAuthoringHarnessReportArtifact              = "authoring_harness_report"
	StandardAuthoringHarnessReportSchemaVersion         = "harbor.standard-authoring-harness-report.v1"
)

var standardAuthoringStageOrder = []workflowkit.StageKey{
	workflowkit.StageKey(RepoPrepare),
	workflowkit.StageKey(RepoAnalyze),
	workflowkit.StageKey(TaskDesign),
	workflowkit.StageKey(TaskReview),
	workflowkit.StageKey(GenerateTaskFiles),
	workflowkit.StageKey(InstructionGen),
	workflowkit.StageKey(TaskTOMLGen),
	workflowkit.StageKey(DockerfileGen),
	workflowkit.StageKey(ContentReview),
	workflowkit.StageKey(SolveGen),
	workflowkit.StageKey(TestGen),
	workflowkit.StageKey(TestsAnalysis),
	workflowkit.StageKey(SolutionReview),
	workflowkit.StageKey(MaterializeTask),
}

var standardAuthoringGroups = []StageGroup{
	StageSourcePrepare,
	StageTaskAnalysis,
	StageTaskDesign,
	StageTaskGeneration,
}

// StandardAuthoringTemplateReference returns the exact closed pre-task
// authoring template. It must never be treated as a partial spelling of the
// full Standard lifecycle template.
func StandardAuthoringTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringWorkflowTemplateVersion}
}

func StandardAuthoringTaskAdmissionTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringTaskAdmissionTemplateVersion}
}

func StandardAuthoringBriefTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringBriefTemplateVersion}
}

func StandardAuthoringRepairFeedbackTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringRepairFeedbackTemplateVersion}
}

func StandardAuthoringTestsAnalysisInputTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringTestsAnalysisInputTemplateVersion}
}

func StandardAuthoringHarnessTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringHarnessTemplateVersion}
}

func StandardAuthoringFixedFileTemplateReference() TemplateReference {
	return TemplateReference{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringFixedFileTemplateVersion}
}

// StandardAuthoringCurrentTemplateReference returns the only authoring
// template new production Runs may select. Historical constructors remain
// explicit and independently resolvable.
func StandardAuthoringCurrentTemplateReference() TemplateReference {
	return StandardAuthoringFixedFileTemplateReference()
}

// IsStandardAuthoringWorkflowTemplate reports whether a Run is bound to the
// immutable-source authoring half of the lifecycle.
func IsStandardAuthoringWorkflowTemplate(reference TemplateReference) bool {
	return reference.Equal(StandardAuthoringTemplateReference()) ||
		reference.Equal(StandardAuthoringTaskAdmissionTemplateReference()) ||
		reference.Equal(StandardAuthoringBriefTemplateReference()) ||
		reference.Equal(StandardAuthoringRepairFeedbackTemplateReference()) ||
		reference.Equal(StandardAuthoringTestsAnalysisInputTemplateReference()) ||
		reference.Equal(StandardAuthoringHarnessTemplateReference()) ||
		reference.Equal(StandardAuthoringFixedFileTemplateReference())
}

// StandardAuthoringStageOrder returns the dependency-aware closed stage list.
func StandardAuthoringStageOrder() []workflowkit.StageKey {
	return append([]workflowkit.StageKey(nil), standardAuthoringStageOrder...)
}

// StandardAuthoringTaskAdmissionStageOrder is the additive 1.3.0 topology.
// Keep this distinct from the legacy order so old deployment catalogs cannot
// accidentally acquire a new required operation.
func StandardAuthoringTaskAdmissionStageOrder() []workflowkit.StageKey {
	order := StandardAuthoringStageOrder()
	for index, key := range order {
		if key == workflowkit.StageKey(SolutionReview) {
			return append(order[:index], append([]workflowkit.StageKey{workflowkit.StageKey(CodeEdgePackageAdmission)}, order[index:]...)...)
		}
	}
	panic("Standard authoring stage order omits solution_review")
}

// StandardAuthoringHarnessStageOrder is the 1.7.0 topology. The build
// validator runs before content review so reviewers see the exact admitted
// Dockerfile. The full harness runs only after independent solution and test
// generation, and tests_analysis consumes its validated test artifact.
func StandardAuthoringHarnessStageOrder() []workflowkit.StageKey {
	return []workflowkit.StageKey{
		workflowkit.StageKey(RepoPrepare),
		workflowkit.StageKey(RepoAnalyze),
		workflowkit.StageKey(TaskDesign),
		workflowkit.StageKey(TaskReview),
		workflowkit.StageKey(GenerateTaskFiles),
		workflowkit.StageKey(InstructionGen),
		workflowkit.StageKey(TaskTOMLGen),
		workflowkit.StageKey(DockerfileGen),
		workflowkit.StageKey(DockerfileBuildValidate),
		workflowkit.StageKey(ContentReview),
		workflowkit.StageKey(SolveGen),
		workflowkit.StageKey(TestGen),
		workflowkit.StageKey(AuthoringHarness),
		workflowkit.StageKey(TestsAnalysis),
		workflowkit.StageKey(CodeEdgePackageAdmission),
		workflowkit.StageKey(SolutionReview),
		workflowkit.StageKey(MaterializeTask),
	}
}

// StandardAuthoringFixedFileStageOrder is intentionally identical to 1.7.0:
// only the pre-harness script submission medium changes in 1.8.0.
func StandardAuthoringFixedFileStageOrder() []workflowkit.StageKey {
	return StandardAuthoringHarnessStageOrder()
}

// StandardAuthoringStageOrderForTemplate exposes the exact closed operation
// set for each installed Authoring template version.
func StandardAuthoringStageOrderForTemplate(reference TemplateReference) ([]workflowkit.StageKey, error) {
	switch {
	case reference.Equal(StandardAuthoringTemplateReference()):
		return StandardAuthoringStageOrder(), nil
	case reference.Equal(StandardAuthoringTaskAdmissionTemplateReference()):
		return StandardAuthoringTaskAdmissionStageOrder(), nil
	case reference.Equal(StandardAuthoringBriefTemplateReference()):
		return StandardAuthoringTaskAdmissionStageOrder(), nil
	case reference.Equal(StandardAuthoringRepairFeedbackTemplateReference()):
		return StandardAuthoringTaskAdmissionStageOrder(), nil
	case reference.Equal(StandardAuthoringTestsAnalysisInputTemplateReference()):
		return StandardAuthoringTaskAdmissionStageOrder(), nil
	case reference.Equal(StandardAuthoringHarnessTemplateReference()):
		return StandardAuthoringHarnessStageOrder(), nil
	case reference.Equal(StandardAuthoringFixedFileTemplateReference()):
		return StandardAuthoringFixedFileStageOrder(), nil
	default:
		return nil, fmt.Errorf("Standard authoring template %s@%s is not installed", reference.ID, reference.Version)
	}
}

func standardAuthoringStageGroups() []StageGroup {
	return append([]StageGroup(nil), standardAuthoringGroups...)
}

func standardAuthoringDependencies() map[workflowkit.StageKey][]workflowkit.StageKey {
	return map[workflowkit.StageKey][]workflowkit.StageKey{
		workflowkit.StageKey(RepoPrepare):       nil,
		workflowkit.StageKey(RepoAnalyze):       {workflowkit.StageKey(RepoPrepare)},
		workflowkit.StageKey(TaskDesign):        {workflowkit.StageKey(RepoAnalyze)},
		workflowkit.StageKey(TaskReview):        {workflowkit.StageKey(TaskDesign)},
		workflowkit.StageKey(GenerateTaskFiles): {workflowkit.StageKey(TaskReview)},
		workflowkit.StageKey(InstructionGen):    {workflowkit.StageKey(GenerateTaskFiles)},
		workflowkit.StageKey(TaskTOMLGen):       {workflowkit.StageKey(GenerateTaskFiles)},
		workflowkit.StageKey(DockerfileGen):     {workflowkit.StageKey(GenerateTaskFiles)},
		workflowkit.StageKey(ContentReview): {
			workflowkit.StageKey(InstructionGen), workflowkit.StageKey(TaskTOMLGen), workflowkit.StageKey(DockerfileGen),
		},
		workflowkit.StageKey(SolveGen):      {workflowkit.StageKey(ContentReview)},
		workflowkit.StageKey(TestGen):       {workflowkit.StageKey(ContentReview)},
		workflowkit.StageKey(TestsAnalysis): {workflowkit.StageKey(ContentReview)},
		workflowkit.StageKey(SolutionReview): {
			workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen), workflowkit.StageKey(TestsAnalysis),
		},
		workflowkit.StageKey(MaterializeTask): {workflowkit.StageKey(SolutionReview)},
	}
}

func standardAuthoringTaskAdmissionDependencies() map[workflowkit.StageKey][]workflowkit.StageKey {
	dependencies := standardAuthoringDependencies()
	dependencies[workflowkit.StageKey(CodeEdgePackageAdmission)] = []workflowkit.StageKey{
		workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen), workflowkit.StageKey(TestsAnalysis),
	}
	dependencies[workflowkit.StageKey(SolutionReview)] = []workflowkit.StageKey{
		workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen), workflowkit.StageKey(CodeEdgePackageAdmission),
	}
	return dependencies
}

func standardAuthoringTestsAnalysisInputDependencies() map[workflowkit.StageKey][]workflowkit.StageKey {
	dependencies := standardAuthoringTaskAdmissionDependencies()
	dependencies[workflowkit.StageKey(TestsAnalysis)] = []workflowkit.StageKey{workflowkit.StageKey(TestGen)}
	return dependencies
}

func standardAuthoringHarnessDependencies() map[workflowkit.StageKey][]workflowkit.StageKey {
	dependencies := standardAuthoringTaskAdmissionDependencies()
	dependencies[workflowkit.StageKey(DockerfileBuildValidate)] = []workflowkit.StageKey{workflowkit.StageKey(DockerfileGen)}
	dependencies[workflowkit.StageKey(ContentReview)] = []workflowkit.StageKey{
		workflowkit.StageKey(InstructionGen), workflowkit.StageKey(TaskTOMLGen), workflowkit.StageKey(DockerfileBuildValidate),
	}
	dependencies[workflowkit.StageKey(AuthoringHarness)] = []workflowkit.StageKey{
		workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen),
	}
	dependencies[workflowkit.StageKey(TestsAnalysis)] = []workflowkit.StageKey{workflowkit.StageKey(AuthoringHarness)}
	dependencies[workflowkit.StageKey(CodeEdgePackageAdmission)] = []workflowkit.StageKey{
		workflowkit.StageKey(AuthoringHarness), workflowkit.StageKey(TestsAnalysis),
	}
	dependencies[workflowkit.StageKey(SolutionReview)] = []workflowkit.StageKey{
		workflowkit.StageKey(AuthoringHarness), workflowkit.StageKey(TestsAnalysis), workflowkit.StageKey(CodeEdgePackageAdmission),
	}
	return dependencies
}

// StandardAuthoringWorkflowTemplate returns the source-session half of task
// creation. It intentionally ends at materialize_task: verification, model
// evaluation, compliance, and packaging must run in a fresh task-bound child
// Run after the immutable handoff has been persisted.
func StandardAuthoringWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{
		ID:          StandardAuthoringWorkflowTemplateID,
		Version:     StandardAuthoringWorkflowTemplateVersion,
		Catalog:     StandardAuthoringStageCatalog(),
		QuotaPolicy: StandardAuthoringQuotaPolicy(),
	}
}

func StandardAuthoringTaskAdmissionWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringTaskAdmissionTemplateVersion, Catalog: StandardAuthoringTaskAdmissionStageCatalog(), QuotaPolicy: StandardAuthoringTaskAdmissionQuotaPolicy()}
}

// StandardAuthoringBriefWorkflowTemplate is the historical 1.4.0 authoring
// contract. It keeps the 1.3.0 admission topology and adds only the frozen
// brief input.
func StandardAuthoringBriefWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{ID: StandardAuthoringWorkflowTemplateID, Version: StandardAuthoringBriefTemplateVersion, Catalog: StandardAuthoringBriefStageCatalog(), QuotaPolicy: StandardAuthoringBriefQuotaPolicy()}
}

// StandardAuthoringRepairFeedbackWorkflowTemplate is the 1.5.0 authoring
// contract. Repair feedback is an optional frozen input because it is absent
// on the first execution and present only after a downstream durable decision.
func StandardAuthoringRepairFeedbackWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{
		ID:          StandardAuthoringWorkflowTemplateID,
		Version:     StandardAuthoringRepairFeedbackTemplateVersion,
		Catalog:     StandardAuthoringRepairFeedbackStageCatalog(),
		QuotaPolicy: StandardAuthoringRepairFeedbackQuotaPolicy(),
	}
}

// StandardAuthoringTestsAnalysisInputWorkflowTemplate is the 1.6.0 authoring
// contract. It preserves the 1.5.0 repair-feedback matrix while binding the
// solution and test generators to the reviewed Dockerfile and tests_analysis to
// the regenerated test script.
func StandardAuthoringTestsAnalysisInputWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{
		ID:          StandardAuthoringWorkflowTemplateID,
		Version:     StandardAuthoringTestsAnalysisInputTemplateVersion,
		Catalog:     StandardAuthoringTestsAnalysisInputStageCatalog(),
		QuotaPolicy: StandardAuthoringTestsAnalysisInputQuotaPolicy(),
	}
}

// StandardAuthoringHarnessWorkflowTemplate is the 1.7.0 authoring contract.
// Its two ReAct stages operate on disposable workspaces while durable lineage
// continues to carry only immutable validated artifacts and bounded reports.
func StandardAuthoringHarnessWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{
		ID:          StandardAuthoringWorkflowTemplateID,
		Version:     StandardAuthoringHarnessTemplateVersion,
		Catalog:     StandardAuthoringHarnessStageCatalog(),
		QuotaPolicy: StandardAuthoringHarnessQuotaPolicy(),
	}
}

// StandardAuthoringFixedFileWorkflowTemplate is the 1.8.0 authoring
// contract. Its topology is intentionally the same as 1.7.0: solve_generate
// and test_generate still feed the writable Docker ReAct authoring_harness,
// but their first artifacts are host-read fixed files rather than model-owned
// base64 tool payloads.
func StandardAuthoringFixedFileWorkflowTemplate() WorkflowTemplate {
	return WorkflowTemplate{
		ID:          StandardAuthoringWorkflowTemplateID,
		Version:     StandardAuthoringFixedFileTemplateVersion,
		Catalog:     StandardAuthoringFixedFileStageCatalog(),
		QuotaPolicy: StandardAuthoringFixedFileQuotaPolicy(),
	}
}

func StandardAuthoringCurrentWorkflowTemplate() WorkflowTemplate {
	return StandardAuthoringFixedFileWorkflowTemplate()
}

func StandardAuthoringTestsAnalysisInputStageCatalog() StageCatalog {
	base := StandardAuthoringRepairFeedbackStageCatalog()
	stages := make([]StageDefinition, 0, len(base.Stages))
	for _, definition := range base.Stages {
		definition = definition.Clone()
		switch definition.Key {
		case workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen):
			definition.Inputs = append(definition.Inputs, artifactInput("dockerfile").spec)
			definition.ReadSet = append(definition.ReadSet, resourceTaskEnvironment)
		case workflowkit.StageKey(TestsAnalysis):
			definition.Dependencies = []workflowkit.StageKey{workflowkit.StageKey(TestGen)}
			definition.Inputs = append(definition.Inputs, artifactInput("test_script").spec)
			definition.ReadSet = append(definition.ReadSet, resourceTaskTests)
			definition.Verdicts = passOnly()
		}
		stages = append(stages, definition)
	}
	return StageCatalog{
		Template: StandardAuthoringTestsAnalysisInputTemplateReference(),
		ID:       standardAuthoringCatalogID,
		Version:  StandardAuthoringTestsAnalysisInputTemplateVersion,
		Stages:   stages,
	}
}

// StandardAuthoringHarnessStageCatalog adds two independent validation
// producers without reusing the upstream artifact keys. Distinct validated_*
// ports are required because StageAttempt ordinals are scoped to a producer;
// selecting the "latest" same-named artifact across different stages would be
// ambiguous after an upstream repair creates ordinal 2 while a downstream
// validator is still at ordinal 1.
func StandardAuthoringHarnessStageCatalog() StageCatalog {
	base := StandardAuthoringTestsAnalysisInputStageCatalog()
	stages := make([]StageDefinition, 0, len(base.Stages)+2)
	for _, definition := range base.Stages {
		definition = definition.Clone()
		if definition.Key == workflowkit.StageKey(ContentReview) {
			validator := stage(
				DockerfileBuildValidate,
				StageTaskGeneration,
				[]string{DockerfileGen},
				"harborfactory.dockerfile_build_validate",
				[]workflowkit.ResourceKey{
					resourceSourceSnapshot, resourceTaskDesign, resourceTaskEnvironment,
					resourceAuthoringEnvironmentPolicy, resourceAuthoringBrief,
				},
				[]workflowkit.ResourceKey{resourceTaskValidatedEnvironment, resourceEvidenceAuthoringDockerBuild},
				workflowkit.EffectContentMutator,
				1,
				passOnly(),
				artifactInput("repo_prepared"),
				artifactInput("task_proposal"),
				artifactInput("dockerfile"),
				standardAuthoringEnvironmentPolicyInput(),
				standardAuthoringBriefInput(),
				artifactOutput(StandardAuthoringValidatedDockerfileArtifact),
				artifactOutputWithSchema(StandardAuthoringDockerfileBuildReportArtifact, StandardAuthoringDockerfileBuildReportSchemaVersion),
			)
			validator = addStandardAuthoringRepairFeedback(validator)
			stages = append(stages, validator)
		}

		switch definition.Key {
		case workflowkit.StageKey(ContentReview):
			definition.Dependencies = []workflowkit.StageKey{
				workflowkit.StageKey(InstructionGen), workflowkit.StageKey(TaskTOMLGen), workflowkit.StageKey(DockerfileBuildValidate),
			}
			replaceStandardAuthoringArtifactInput(&definition, "dockerfile", artifactInput(StandardAuthoringValidatedDockerfileArtifact).spec)
			replaceStandardAuthoringReadResource(&definition, resourceTaskEnvironment, resourceTaskValidatedEnvironment)
			definition.Inputs = append(definition.Inputs, artifactInputWithSchema(StandardAuthoringDockerfileBuildReportArtifact, StandardAuthoringDockerfileBuildReportSchemaVersion).spec)
			definition.ReadSet = append(definition.ReadSet, resourceEvidenceAuthoringDockerBuild)
		case workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen):
			replaceStandardAuthoringArtifactInput(&definition, "dockerfile", artifactInput(StandardAuthoringValidatedDockerfileArtifact).spec)
			replaceStandardAuthoringReadResource(&definition, resourceTaskEnvironment, resourceTaskValidatedEnvironment)
			definition.Inputs = append(definition.Inputs, artifactInputWithSchema(StandardAuthoringDockerfileBuildReportArtifact, StandardAuthoringDockerfileBuildReportSchemaVersion).spec)
			definition.ReadSet = append(definition.ReadSet, resourceEvidenceAuthoringDockerBuild)
		case workflowkit.StageKey(TestsAnalysis):
			harness := stage(
				AuthoringHarness,
				StageTaskGeneration,
				[]string{SolveGen, TestGen},
				"harborfactory.authoring_harness",
				[]workflowkit.ResourceKey{
					resourceSourceSnapshot, resourceTaskGeneratedFiles, resourceTaskDesign,
					resourceTaskInstruction, resourceTaskMetadata, resourceTaskValidatedEnvironment,
					resourceTaskSolution, resourceTaskTests, resourceEvidenceAuthoringDockerBuild,
					resourceAuthoringEnvironmentPolicy, resourceAuthoringBrief,
				},
				[]workflowkit.ResourceKey{resourceTaskValidatedSolution, resourceTaskValidatedTests, resourceEvidenceAuthoringHarness},
				workflowkit.EffectContentMutator,
				1,
				passOnly(),
				artifactInput("repo_prepared"),
				artifactInput("generated_task_files"),
				artifactInput("task_proposal"),
				artifactInput("instruction"),
				artifactInput("task_toml"),
				artifactInput(StandardAuthoringValidatedDockerfileArtifact),
				artifactInputWithSchema(StandardAuthoringDockerfileBuildReportArtifact, StandardAuthoringDockerfileBuildReportSchemaVersion),
				artifactInput("solve_script"),
				artifactInput("test_script"),
				standardAuthoringEnvironmentPolicyInput(),
				standardAuthoringBriefInput(),
				artifactOutput(StandardAuthoringValidatedSolveScriptArtifact),
				artifactOutput(StandardAuthoringValidatedTestScriptArtifact),
				artifactOutputWithSchema(StandardAuthoringHarnessReportArtifact, StandardAuthoringHarnessReportSchemaVersion),
			)
			harness = addStandardAuthoringRepairFeedback(harness)
			stages = append(stages, harness)

			definition.Dependencies = []workflowkit.StageKey{workflowkit.StageKey(AuthoringHarness)}
			replaceStandardAuthoringArtifactInput(&definition, "test_script", artifactInput(StandardAuthoringValidatedTestScriptArtifact).spec)
			replaceStandardAuthoringReadResource(&definition, resourceTaskTests, resourceTaskValidatedTests)
			definition.Inputs = append(definition.Inputs, artifactInputWithSchema(StandardAuthoringHarnessReportArtifact, StandardAuthoringHarnessReportSchemaVersion).spec)
			definition.ReadSet = append(definition.ReadSet, resourceEvidenceAuthoringHarness)
		case workflowkit.StageKey(CodeEdgePackageAdmission):
			definition.Dependencies = []workflowkit.StageKey{workflowkit.StageKey(AuthoringHarness), workflowkit.StageKey(TestsAnalysis)}
			replaceStandardAuthoringPackageInputs(&definition)
			definition.Inputs = append(definition.Inputs,
				artifactInputWithSchema(StandardAuthoringDockerfileBuildReportArtifact, StandardAuthoringDockerfileBuildReportSchemaVersion).spec,
				artifactInputWithSchema(StandardAuthoringHarnessReportArtifact, StandardAuthoringHarnessReportSchemaVersion).spec,
			)
			definition.ReadSet = append(definition.ReadSet, resourceEvidenceAuthoringDockerBuild, resourceEvidenceAuthoringHarness)
		case workflowkit.StageKey(SolutionReview):
			definition.Dependencies = []workflowkit.StageKey{
				workflowkit.StageKey(AuthoringHarness), workflowkit.StageKey(TestsAnalysis), workflowkit.StageKey(CodeEdgePackageAdmission),
			}
			replaceStandardAuthoringArtifactInput(&definition, "solve_script", artifactInput(StandardAuthoringValidatedSolveScriptArtifact).spec)
			replaceStandardAuthoringArtifactInput(&definition, "test_script", artifactInput(StandardAuthoringValidatedTestScriptArtifact).spec)
			replaceStandardAuthoringReadResource(&definition, resourceTaskSolution, resourceTaskValidatedSolution)
			replaceStandardAuthoringReadResource(&definition, resourceTaskTests, resourceTaskValidatedTests)
			definition.Inputs = append(definition.Inputs, artifactInputWithSchema(StandardAuthoringHarnessReportArtifact, StandardAuthoringHarnessReportSchemaVersion).spec)
			definition.ReadSet = append(definition.ReadSet, resourceEvidenceAuthoringHarness)
		case workflowkit.StageKey(MaterializeTask):
			replaceStandardAuthoringPackageInputs(&definition)
			definition.Inputs = append(definition.Inputs,
				artifactInputWithSchema(StandardAuthoringDockerfileBuildReportArtifact, StandardAuthoringDockerfileBuildReportSchemaVersion).spec,
				artifactInputWithSchema(StandardAuthoringHarnessReportArtifact, StandardAuthoringHarnessReportSchemaVersion).spec,
			)
			definition.ReadSet = append(definition.ReadSet, resourceEvidenceAuthoringDockerBuild, resourceEvidenceAuthoringHarness)
		}
		stages = append(stages, definition)
	}
	return StageCatalog{
		Template: StandardAuthoringHarnessTemplateReference(),
		ID:       standardAuthoringCatalogID,
		Version:  StandardAuthoringHarnessTemplateVersion,
		Stages:   stages,
	}
}

// StandardAuthoringFixedFileStageCatalog is the additive 1.8.0 catalog. It
// clones the closed 1.7.0 graph rather than re-deriving it, making a topology
// change impossible here. The only descriptor-level semantic difference is
// that fixed-file script producers can complete only with a host-validated
// pass; needs_repair/reject bytes have no fixed-file representation.
func StandardAuthoringFixedFileStageCatalog() StageCatalog {
	base := StandardAuthoringHarnessStageCatalog()
	stages := make([]StageDefinition, len(base.Stages))
	for index, definition := range base.Stages {
		definition = definition.Clone()
		switch definition.Key {
		case workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen):
			definition.Verdicts = passOnly()
		}
		stages[index] = definition
	}
	return StageCatalog{
		Template: StandardAuthoringFixedFileTemplateReference(),
		ID:       standardAuthoringCatalogID,
		Version:  StandardAuthoringFixedFileTemplateVersion,
		Stages:   stages,
	}
}

func addStandardAuthoringRepairFeedback(definition StageDefinition) StageDefinition {
	for _, feedback := range standardAuthoringRepairFeedbackForStage(definition.Key) {
		definition.Inputs = append(definition.Inputs, feedback.input)
		definition.ReadSet = append(definition.ReadSet, feedback.resource)
	}
	return definition
}

func replaceStandardAuthoringPackageInputs(definition *StageDefinition) {
	replaceStandardAuthoringArtifactInput(definition, "dockerfile", artifactInput(StandardAuthoringValidatedDockerfileArtifact).spec)
	replaceStandardAuthoringArtifactInput(definition, "solve_script", artifactInput(StandardAuthoringValidatedSolveScriptArtifact).spec)
	replaceStandardAuthoringArtifactInput(definition, "test_script", artifactInput(StandardAuthoringValidatedTestScriptArtifact).spec)
	replaceStandardAuthoringReadResource(definition, resourceTaskEnvironment, resourceTaskValidatedEnvironment)
	replaceStandardAuthoringReadResource(definition, resourceTaskSolution, resourceTaskValidatedSolution)
	replaceStandardAuthoringReadResource(definition, resourceTaskTests, resourceTaskValidatedTests)
}

func replaceStandardAuthoringArtifactInput(definition *StageDefinition, name string, replacement workflowkit.ArtifactSpec) {
	for index := range definition.Inputs {
		if definition.Inputs[index].Name == name {
			definition.Inputs[index] = replacement
			return
		}
	}
	panic("Standard authoring catalog is missing required artifact input " + name)
}

func replaceStandardAuthoringReadResource(definition *StageDefinition, current, replacement workflowkit.ResourceKey) {
	for index := range definition.ReadSet {
		if definition.ReadSet[index] == current {
			definition.ReadSet[index] = replacement
			return
		}
	}
	panic("Standard authoring catalog is missing required read resource " + string(current))
}

func StandardAuthoringRepairFeedbackStageCatalog() StageCatalog {
	base := StandardAuthoringBriefStageCatalog()
	stages := make([]StageDefinition, 0, len(base.Stages))
	for _, definition := range base.Stages {
		definition = definition.Clone()
		for _, feedback := range standardAuthoringRepairFeedbackForStage(definition.Key) {
			definition.Inputs = append(definition.Inputs, feedback.input)
			definition.ReadSet = append(definition.ReadSet, feedback.resource)
		}
		stages = append(stages, definition)
	}
	return StageCatalog{
		Template: StandardAuthoringRepairFeedbackTemplateReference(),
		ID:       standardAuthoringCatalogID,
		Version:  StandardAuthoringRepairFeedbackTemplateVersion,
		Stages:   stages,
	}
}

func StandardAuthoringBriefStageCatalog() StageCatalog {
	base := StandardAuthoringTaskAdmissionStageCatalog()
	stages := make([]StageDefinition, 0, len(base.Stages))
	for _, definition := range base.Stages {
		definition = definition.Clone()
		if standardAuthoringStageUsesBrief(definition.Key) {
			definition.Inputs = append(definition.Inputs, standardAuthoringBriefInput().spec)
			definition.ReadSet = append(definition.ReadSet, resourceAuthoringBrief)
		}
		stages = append(stages, definition)
	}
	return StageCatalog{Template: StandardAuthoringBriefTemplateReference(), ID: standardAuthoringCatalogID, Version: StandardAuthoringBriefTemplateVersion, Stages: stages}
}

func StandardAuthoringTaskAdmissionStageCatalog() StageCatalog {
	base := StandardAuthoringStageCatalog()
	stages := make([]StageDefinition, 0, len(base.Stages)+1)
	for _, definition := range base.Stages {
		definition = definition.Clone()
		if definition.Key == workflowkit.StageKey(SolutionReview) {
			stages = append(stages, stage(CodeEdgePackageAdmission, StageTaskGeneration, []string{SolveGen, TestGen, TestsAnalysis}, "harborfactory.codeedge_package_admission", []workflowkit.ResourceKey{resourceTaskInstruction, resourceTaskMetadata, resourceTaskEnvironment, resourceTaskSolution, resourceTaskTests, resourceTaskTestsAnalysis, resourceAuthoringEnvironmentPolicy}, []workflowkit.ResourceKey{resourceAuthoringTaskAdmission}, workflowkit.EffectEvidenceOnly, 1, contentVerdicts(), artifactInput("instruction"), artifactInput("task_toml"), artifactInput("dockerfile"), standardAuthoringEnvironmentPolicyInput(), artifactInput("solve_script"), artifactInput("test_script"), artifactInput("tests_analysis"), artifactOutputWithSchema("codeedge_package_admission_report", "harbor.standard-authoring-task-package-admission.v1")))
			definition.Dependencies = []workflowkit.StageKey{workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen), workflowkit.StageKey(CodeEdgePackageAdmission)}
			definition.Inputs = append(definition.Inputs, artifactInputWithSchema("codeedge_package_admission_report", "harbor.standard-authoring-task-package-admission.v1").spec)
			definition.ReadSet = append(definition.ReadSet, resourceAuthoringTaskAdmission)
		}
		if definition.Key == workflowkit.StageKey(MaterializeTask) {
			definition.Inputs = append(definition.Inputs, artifactInputWithSchema("codeedge_package_admission_report", "harbor.standard-authoring-task-package-admission.v1").spec)
			definition.ReadSet = append(definition.ReadSet, resourceAuthoringTaskAdmission)
			for index := range definition.Outputs {
				if definition.Outputs[index].Name == StandardAuthoringTaskHandoffArtifact {
					definition.Outputs[index].SchemaVersion = StandardAuthoringTaskAdmissionHandoffSchemaVersion
				}
			}
		}
		stages = append(stages, definition)
	}
	return StageCatalog{Template: StandardAuthoringTaskAdmissionTemplateReference(), ID: standardAuthoringCatalogID, Version: StandardAuthoringTaskAdmissionTemplateVersion, Stages: stages}
}

func StandardAuthoringTaskHandoffSchemaForTemplate(reference TemplateReference) (string, error) {
	switch {
	case reference.Equal(StandardAuthoringTemplateReference()):
		return StandardAuthoringTaskHandoffSchemaVersion, nil
	case reference.Equal(StandardAuthoringTaskAdmissionTemplateReference()):
		return StandardAuthoringTaskAdmissionHandoffSchemaVersion, nil
	case reference.Equal(StandardAuthoringBriefTemplateReference()):
		return StandardAuthoringTaskAdmissionHandoffSchemaVersion, nil
	case reference.Equal(StandardAuthoringRepairFeedbackTemplateReference()):
		return StandardAuthoringTaskAdmissionHandoffSchemaVersion, nil
	case reference.Equal(StandardAuthoringTestsAnalysisInputTemplateReference()):
		return StandardAuthoringTaskAdmissionHandoffSchemaVersion, nil
	case reference.Equal(StandardAuthoringHarnessTemplateReference()):
		return StandardAuthoringTaskAdmissionHandoffSchemaVersion, nil
	case reference.Equal(StandardAuthoringFixedFileTemplateReference()):
		return StandardAuthoringTaskAdmissionHandoffSchemaVersion, nil
	default:
		return "", fmt.Errorf("Standard authoring handoff schema has no template %s@%s", reference.ID, reference.Version)
	}
}

// StandardAuthoringStageCatalog derives the source-session catalog from the
// canonical StandardStageCatalog. It overlays the required immutable
// environment-policy input before materialize_task emits the handoff receipt.
func StandardAuthoringStageCatalog() StageCatalog {
	canonical := StandardStageCatalog()
	stages := make([]StageDefinition, 0, len(canonical.Stages))
	for _, definition := range canonical.Stages[:13] {
		definition = definition.Clone()
		if definition.Key == workflowkit.StageKey(TaskDesign) {
			definition.RequiredTurns = StandardAuthoringTaskDesignMaxTurns
		}
		if standardAuthoringStageUsesEnvironmentPolicy(definition.Key) {
			definition.Inputs = append(definition.Inputs, standardAuthoringEnvironmentPolicyInput().spec)
			definition.ReadSet = append(definition.ReadSet, resourceAuthoringEnvironmentPolicy)
		}
		stages = append(stages, definition)
	}
	stages = append(stages,
		stage(MaterializeTask, StageTaskGeneration, []string{SolutionReview}, "harborfactory.materialize_task",
			[]workflowkit.ResourceKey{resourceTaskInstruction, resourceTaskMetadata, resourceTaskEnvironment, resourceTaskSolution, resourceTaskTests, resourceTaskTestsAnalysis, resourceReviewSolutionVerifier, resourceAuthoringEnvironmentPolicy},
			[]workflowkit.ResourceKey{resourceTaskSnapshot, resourceTaskDigest, resourceTaskInstruction, resourceTaskMetadata, resourceTaskEnvironment, resourceTaskSolution, resourceTaskTests, resourceTaskTestsAnalysis, resourceAuthoringTaskHandoff},
			workflowkit.EffectContentMutator, 1, contentVerdicts(),
			artifactInput("instruction"), artifactInput("task_toml"), artifactInput("dockerfile"), standardAuthoringEnvironmentPolicyInput(),
			artifactInput("solve_script"), artifactInput("test_script"), artifactInput("tests_analysis"),
			reviewDecisionInput("solution_review_decision"),
			artifactOutput("task_snapshot"), artifactOutput("task_digest"),
			artifactOutputWithSchema(StandardAuthoringTaskHandoffArtifact, StandardAuthoringTaskHandoffSchemaVersion),
		),
	)
	return StageCatalog{
		Template: StandardAuthoringTemplateReference(),
		ID:       standardAuthoringCatalogID,
		Version:  standardAuthoringCatalogVersion,
		Stages:   stages,
	}
}

func standardAuthoringStageUsesEnvironmentPolicy(key workflowkit.StageKey) bool {
	switch key {
	case workflowkit.StageKey(TaskDesign), workflowkit.StageKey(GenerateTaskFiles), workflowkit.StageKey(DockerfileGen),
		workflowkit.StageKey(DockerfileBuildValidate), workflowkit.StageKey(ContentReview), workflowkit.StageKey(AuthoringHarness):
		return true
	default:
		return false
	}
}

func standardAuthoringEnvironmentPolicyInput() stageArtifact {
	return artifactInputWithSchema(StandardAuthoringEnvironmentPolicyArtifact, StandardAuthoringEnvironmentPolicySchemaVersion)
}

func standardAuthoringStageUsesBrief(key workflowkit.StageKey) bool {
	switch key {
	case workflowkit.StageKey(RepoAnalyze), workflowkit.StageKey(TaskDesign), workflowkit.StageKey(GenerateTaskFiles),
		workflowkit.StageKey(TaskTOMLGen), workflowkit.StageKey(DockerfileBuildValidate), workflowkit.StageKey(ContentReview),
		workflowkit.StageKey(AuthoringHarness), workflowkit.StageKey(CodeEdgePackageAdmission),
		workflowkit.StageKey(MaterializeTask):
		return true
	default:
		return false
	}
}

func standardAuthoringBriefInput() stageArtifact {
	return artifactInputWithSchema(StandardAuthoringBriefArtifact, StandardAuthoringBriefSchemaVersion)
}

type standardAuthoringRepairFeedback struct {
	input    workflowkit.ArtifactSpec
	resource workflowkit.ResourceKey
}

func standardAuthoringRepairFeedbackForStage(key workflowkit.StageKey) []standardAuthoringRepairFeedback {
	feedback := make([]standardAuthoringRepairFeedback, 0, 3)
	if key == workflowkit.StageKey(RepoAnalyze) || key == workflowkit.StageKey(TaskDesign) {
		feedback = append(feedback, standardAuthoringRepairFeedback{
			input:    optionalReviewDecisionInput("task_review_decision").spec,
			resource: resourceReviewTaskDirection,
		})
	}
	if key == workflowkit.StageKey(InstructionGen) || key == workflowkit.StageKey(TaskTOMLGen) || key == workflowkit.StageKey(DockerfileGen) || key == workflowkit.StageKey(DockerfileBuildValidate) {
		feedback = append(feedback, standardAuthoringRepairFeedback{
			input:    optionalReviewDecisionInput("content_review_decision").spec,
			resource: resourceReviewContent,
		})
	}
	if standardAuthoringStageRepairsPackageContent(key) {
		feedback = append(feedback,
			standardAuthoringRepairFeedback{
				input:    optionalReviewDecisionInput("solution_review_decision").spec,
				resource: resourceReviewSolutionVerifier,
			},
			standardAuthoringRepairFeedback{
				input:    optionalArtifactInputWithSchema("codeedge_package_admission_report", "harbor.standard-authoring-task-package-admission.v1").spec,
				resource: resourceAuthoringTaskAdmission,
			},
		)
	}
	return feedback
}

func standardAuthoringStageRepairsPackageContent(key workflowkit.StageKey) bool {
	switch key {
	case workflowkit.StageKey(InstructionGen), workflowkit.StageKey(TaskTOMLGen), workflowkit.StageKey(DockerfileGen),
		workflowkit.StageKey(DockerfileBuildValidate), workflowkit.StageKey(SolveGen), workflowkit.StageKey(TestGen),
		workflowkit.StageKey(AuthoringHarness), workflowkit.StageKey(TestsAnalysis):
		return true
	default:
		return false
	}
}
