package app

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/purplevoid/harbor-factory/internal/harbor/stageprovider"
	"github.com/purplevoid/harbor-factory/internal/harbor/store"
	"github.com/purplevoid/harbor-factory/internal/harbor/workflowadapter"
	"github.com/purplevoid/harbor-factory/pkg/workflowkit"
)

var (
	// ErrStandardProtocolStageRetryIneligible marks a failure that must not be
	// retried in-place. Callers should start a new source/session Run instead.
	ErrStandardProtocolStageRetryIneligible = errors.New("standard protocol stage retry is not eligible")
	// ErrStandardProtocolStageRetryStale marks the boundary between a preview
	// and confirmation. It is deliberately distinct from a Store CAS error so
	// presentation layers can request a fresh preview without exposing internals.
	ErrStandardProtocolStageRetryStale = errors.New("standard protocol stage retry preview is stale")
)

// StandardProtocolStageRetryCheckpoint is the immutable operator preview
// basis. It includes the failed StageAttempt, final node/transcript fact and
// complete frozen Run identity; a confirmation never retargets newer state.
type StandardProtocolStageRetryCheckpoint struct {
	RunID               string                  `json:"run_id"`
	RunVersion          int64                   `json:"run_version"`
	RunExecutionEpoch   int                     `json:"run_execution_epoch"`
	RunDefinitionHash   string                  `json:"run_definition_hash"`
	StageAttemptID      string                  `json:"stage_attempt_id"`
	StageAttemptVersion int64                   `json:"stage_attempt_version"`
	NodeAttemptID       string                  `json:"node_attempt_id"`
	NodeAttemptVersion  int64                   `json:"node_attempt_version"`
	TranscriptID        string                  `json:"transcript_id"`
	TranscriptVersion   int64                   `json:"transcript_version"`
	InputFingerprint    workflowkit.Fingerprint `json:"input_fingerprint"`
	FailureCode         string                  `json:"failure_code"`
	RetryFingerprint    workflowkit.Fingerprint `json:"retry_fingerprint"`
}

// StandardProtocolStageRetryPreview is read-only. It exposes the exact
// failed Agent node and retained transcript summary needed by a three-step UI
// confirmation without granting the transcript any output authority.
type StandardProtocolStageRetryPreview struct {
	Run                store.WorkflowRun
	SourceStageAttempt store.StageAttempt
	SourceNodeAttempt  store.NodeAttempt
	Transcript         store.AgentTurnTranscript
	StageKey           workflowkit.StageKey
	SourceGeneration   int
	RetryGeneration    int
	Checkpoint         StandardProtocolStageRetryCheckpoint
}

// StandardProtocolStageRetryCommand confirms one preview. IdempotencyKey is
// a UUIDv7 generated by the caller and retained unchanged after a lost reply.
type StandardProtocolStageRetryCommand struct {
	IdempotencyKey       string
	Actor                string
	Reason               string
	RunID                string
	SourceStageAttemptID string
	Expected             StandardProtocolStageRetryCheckpoint
}

// StandardProtocolStageRetryReceipt contains only durable retry identities.
// A queued worker is activated from the job outbox by the normal run
// activation service, never directly by this mutation.
type StandardProtocolStageRetryReceipt struct {
	Run        store.WorkflowRun
	Source     store.StageAttempt
	Retry      store.StageAttempt
	RunAttempt store.RunAttempt
	Job        store.DurableJob
	Replayed   bool
}

// PreviewStandardProtocolStageRetry proves that a Standard Authoring Agent
// stage failed only because its terminal protocol was not satisfied. It
// resolves the original frozen input graph again and rejects any drift.
func (service *RunService) PreviewStandardProtocolStageRetry(ctx context.Context, runID, stageAttemptID string) (StandardProtocolStageRetryPreview, error) {
	if service == nil || service.core == nil || service.core.store == nil {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("run service is not configured")
	}
	runID = strings.TrimSpace(runID)
	stageAttemptID = strings.TrimSpace(stageAttemptID)
	if err := store.ValidateUUIDv7(runID); err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	if err := store.ValidateUUIDv7(stageAttemptID); err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	run, err := service.core.store.GetWorkflowRun(ctx, runID)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	if run == nil {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: run %s", ErrLifecycleNotFound, runID)
	}
	source, err := service.core.store.GetStageAttempt(ctx, stageAttemptID)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	if source == nil {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: stage attempt %s", ErrLifecycleNotFound, stageAttemptID)
	}
	return service.previewStandardProtocolStageRetry(ctx, *run, *source)
}

// RetryStandardProtocolStage revalidates a preview then atomically creates a
// fresh fenced StageAttempt, job/outbox and run execution epoch. It never
// derives a new source snapshot, candidate, profile or execution definition.
func (service *RunService) RetryStandardProtocolStage(ctx context.Context, command StandardProtocolStageRetryCommand) (StandardProtocolStageRetryReceipt, error) {
	if service == nil || service.core == nil || service.core.store == nil {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("run service is not configured")
	}
	if err := validateStandardProtocolStageRetryCommand(command); err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	jobKey := standardProtocolStageRetryJobKey(command.IdempotencyKey)
	if existing, err := service.core.store.GetDurableJobByIdempotency(ctx, jobKey); err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	} else if existing != nil {
		return service.replayStandardProtocolStageRetry(ctx, command, *existing)
	}

	preview, err := service.PreviewStandardProtocolStageRetry(ctx, command.RunID, command.SourceStageAttemptID)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	if !sameStandardProtocolStageRetryCheckpoint(preview.Checkpoint, command.Expected) {
		return StandardProtocolStageRetryReceipt{}, ErrStandardProtocolStageRetryStale
	}

	retryID, err := store.NewUUIDv7()
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("allocate protocol retry stage attempt identity: %w", err)
	}
	jobID, err := store.NewUUIDv7()
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("allocate protocol retry job identity: %w", err)
	}
	retrySnapshot, err := standardProtocolRetrySnapshot(preview, command)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	payload, err := standardProtocolRetryPayload(preview, retryID)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	commit, err := service.core.store.CommitStageProtocolRetry(ctx, store.CommitStageProtocolRetryRequest{
		SourceStageAttemptID: preview.SourceStageAttempt.ID, ExpectedSourceStageAttemptVersion: preview.SourceStageAttempt.Version,
		ExpectedSourceErrorText: preview.SourceStageAttempt.ErrorText, ExpectedSourceFailureClass: preview.SourceStageAttempt.FailureClass,
		ExpectedRunVersion: preview.Run.Version, ExpectedRunExecutionEpoch: preview.Run.ExecutionEpoch,
		NewStageAttemptID: retryID, NewGeneration: preview.RetryGeneration, RetrySnapshotJSON: retrySnapshot,
		JobID: jobID, JobPayloadJSON: payload, IdempotencyKey: jobKey, Actor: command.Actor, Reason: command.Reason,
	})
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	return standardProtocolStageRetryReceipt(commit), nil
}

func (service *RunService) previewStandardProtocolStageRetry(ctx context.Context, run store.WorkflowRun, source store.StageAttempt) (StandardProtocolStageRetryPreview, error) {
	if run.SubjectKind != store.WorkflowRunSubjectAuthoringSession || !workflowadapter.IsStandardAuthoringWorkflowTemplate(workflowadapter.TemplateReference{ID: run.WorkflowTemplateID, Version: run.WorkflowTemplateVersion}) {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: run %s is not a current Standard authoring source/session Run", ErrStandardProtocolStageRetryIneligible, run.ID)
	}
	if run.Status != store.WorkflowRunFailedRecoverable || source.RunID != run.ID || source.ExecutionStatus != store.StageExecutionInfraFailed || !stageprovider.IsStandardAuthoringProtocolFailure(source.ErrorText) || strings.TrimSpace(source.FailureClass) == "" {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: stage attempt %s is not a protocol-only recoverable failure", ErrStandardProtocolStageRetryIneligible, source.ID)
	}
	frozen, err := decodeFrozenRunDefinition(run)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	stageKey := workflowkit.StageKey(source.StageKey)
	stage, found := frozen.Workflow.Stage(stageKey)
	if !found || !standardProtocolRetryAgentStage(stage) {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: stage %q is not a Standard Agent stage", ErrStandardProtocolStageRetryIneligible, source.StageKey)
	}
	var snapshot runtimeStageAttemptSnapshot
	if err := decodeStrictJSON(source.RetrySnapshotJSON, &snapshot); err != nil || snapshot.Format != runtimeStageAttemptSnapshotFormat || snapshot.ExecutionKey != "initial" || snapshot.ContinuationExecutionID != "" || snapshot.ContinuationPlanID != "" || snapshot.Generation < 0 {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: stage attempt %s has no initial frozen retry binding", ErrStandardProtocolStageRetryIneligible, source.ID)
	}
	subject, err := service.core.resolveWorkflowRunSubject(ctx, run)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	inputs, err := resolveStageInputsForSubjectWithExplicitInputs(ctx, service.core.store, service.core.objects, run, subject, stage, nil)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: frozen inputs for stage %q: %v", ErrStandardProtocolStageRetryIneligible, stage.Key, err)
	}
	inputFingerprint, err := workflowkit.FingerprintArtifactBindings(inputs)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	if inputFingerprint != workflowkit.Fingerprint(source.InputFingerprint) {
		return StandardProtocolStageRetryPreview{}, fmt.Errorf("%w: stage %q frozen input fingerprint drifted", ErrStandardProtocolStageRetryIneligible, stage.Key)
	}
	node, transcript, err := service.standardProtocolRetryNodeAndTranscript(ctx, source, source.ErrorText)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	checkpoint, err := standardProtocolStageRetryCheckpoint(run, source, node, transcript, inputFingerprint, snapshot.Generation+1)
	if err != nil {
		return StandardProtocolStageRetryPreview{}, err
	}
	return StandardProtocolStageRetryPreview{
		Run: run, SourceStageAttempt: source, SourceNodeAttempt: node, Transcript: transcript,
		StageKey: stageKey, SourceGeneration: snapshot.Generation, RetryGeneration: snapshot.Generation + 1, Checkpoint: checkpoint,
	}, nil
}

func standardProtocolRetryAgentStage(stage workflowkit.StageDescriptor) bool {
	return stage.AgentRole != nil && stage.AutomaticallyDispatchable()
}

func (service *RunService) standardProtocolRetryNodeAndTranscript(ctx context.Context, source store.StageAttempt, failureCode string) (store.NodeAttempt, store.AgentTurnTranscript, error) {
	nodes, err := service.core.store.ListNodeAttempts(ctx, source.ID)
	if err != nil {
		return store.NodeAttempt{}, store.AgentTurnTranscript{}, err
	}
	if len(nodes) == 0 {
		return store.NodeAttempt{}, store.AgentTurnTranscript{}, fmt.Errorf("%w: stage attempt %s has no Agent node attempt", ErrStandardProtocolStageRetryIneligible, source.ID)
	}
	node := nodes[len(nodes)-1]
	if node.StageAttemptID != source.ID || node.Status != store.NodeAttemptInfraFailed {
		return store.NodeAttempt{}, store.AgentTurnTranscript{}, fmt.Errorf("%w: stage attempt %s does not end at a failed Agent node", ErrStandardProtocolStageRetryIneligible, source.ID)
	}
	transcripts, err := service.core.store.ListAgentTurnTranscripts(ctx, node.ID)
	if err != nil {
		return store.NodeAttempt{}, store.AgentTurnTranscript{}, err
	}
	for index := len(transcripts) - 1; index >= 0; index-- {
		transcript := transcripts[index]
		if transcript.FailureCode == failureCode && transcript.ProtocolRejectionCode == failureCode {
			return node, transcript, nil
		}
	}
	return store.NodeAttempt{}, store.AgentTurnTranscript{}, fmt.Errorf("%w: stage attempt %s has no matching durable protocol transcript", ErrStandardProtocolStageRetryIneligible, source.ID)
}

func standardProtocolStageRetryCheckpoint(run store.WorkflowRun, source store.StageAttempt, node store.NodeAttempt, transcript store.AgentTurnTranscript, input workflowkit.Fingerprint, retryGeneration int) (StandardProtocolStageRetryCheckpoint, error) {
	fingerprint, err := workflowkit.FingerprintParts("harbor.standard-protocol-stage-retry-preview.v1", []workflowkit.FingerprintPart{
		{Name: "run_id", Value: []byte(run.ID)}, {Name: "run_version", Value: []byte(fmt.Sprintf("%d", run.Version))},
		{Name: "run_execution_epoch", Value: []byte(fmt.Sprintf("%d", run.ExecutionEpoch))}, {Name: "run_definition_hash", Value: []byte(run.DefinitionHash)},
		{Name: "stage_attempt_id", Value: []byte(source.ID)}, {Name: "stage_attempt_version", Value: []byte(fmt.Sprintf("%d", source.Version))},
		{Name: "node_attempt_id", Value: []byte(node.ID)}, {Name: "node_attempt_version", Value: []byte(fmt.Sprintf("%d", node.Version))},
		{Name: "transcript_id", Value: []byte(transcript.ID)}, {Name: "transcript_version", Value: []byte(fmt.Sprintf("%d", transcript.Version))},
		{Name: "input_fingerprint", Value: []byte(input)}, {Name: "failure_code", Value: []byte(source.ErrorText)},
		{Name: "retry_generation", Value: []byte(fmt.Sprintf("%d", retryGeneration))},
	})
	if err != nil {
		return StandardProtocolStageRetryCheckpoint{}, err
	}
	return StandardProtocolStageRetryCheckpoint{
		RunID: run.ID, RunVersion: run.Version, RunExecutionEpoch: run.ExecutionEpoch, RunDefinitionHash: run.DefinitionHash,
		StageAttemptID: source.ID, StageAttemptVersion: source.Version, NodeAttemptID: node.ID, NodeAttemptVersion: node.Version,
		TranscriptID: transcript.ID, TranscriptVersion: transcript.Version, InputFingerprint: input, FailureCode: source.ErrorText, RetryFingerprint: fingerprint,
	}, nil
}

func validateStandardProtocolStageRetryCommand(command StandardProtocolStageRetryCommand) error {
	if err := store.ValidateUUIDv7(strings.TrimSpace(command.IdempotencyKey)); err != nil {
		return err
	}
	if strings.TrimSpace(command.Actor) == "" || strings.TrimSpace(command.Reason) == "" {
		return fmt.Errorf("standard protocol retry actor and reason are required")
	}
	if err := store.ValidateUUIDv7(strings.TrimSpace(command.RunID)); err != nil {
		return err
	}
	if err := store.ValidateUUIDv7(strings.TrimSpace(command.SourceStageAttemptID)); err != nil {
		return err
	}
	if command.Expected.RunID != command.RunID || command.Expected.StageAttemptID != command.SourceStageAttemptID || command.Expected.RunVersion <= 0 || command.Expected.StageAttemptVersion <= 0 || command.Expected.NodeAttemptVersion <= 0 || command.Expected.TranscriptVersion <= 0 || command.Expected.RetryFingerprint == "" {
		return fmt.Errorf("standard protocol retry requires a complete preview checkpoint")
	}
	if err := command.Expected.RetryFingerprint.Validate(); err != nil {
		return err
	}
	return nil
}

func sameStandardProtocolStageRetryCheckpoint(left, right StandardProtocolStageRetryCheckpoint) bool {
	return left == right
}

func standardProtocolRetrySnapshot(preview StandardProtocolStageRetryPreview, command StandardProtocolStageRetryCommand) (string, error) {
	var source runtimeStageAttemptSnapshot
	if err := decodeStrictJSON(preview.SourceStageAttempt.RetrySnapshotJSON, &source); err != nil {
		return "", err
	}
	source.Generation = preview.RetryGeneration
	encoded, err := json.Marshal(source)
	if err != nil {
		return "", err
	}
	return string(encoded), nil
}

func standardProtocolRetryPayload(preview StandardProtocolStageRetryPreview, retryAttemptID string) (string, error) {
	frozen, err := decodeFrozenRunDefinition(preview.Run)
	if err != nil {
		return "", err
	}
	payload, err := json.Marshal(frozenStageExecutionPayload{
		Format: frozenStageExecutionPayloadFormat, RunID: preview.Run.ID, StageAttemptID: retryAttemptID, StageKey: preview.StageKey,
		DefinitionHash: preview.Run.DefinitionHash, Generation: preview.RetryGeneration, QuotaPolicy: frozen.QuotaPolicy.Clone(),
	})
	if err != nil {
		return "", err
	}
	return string(payload), nil
}

func standardProtocolStageRetryJobKey(idempotencyKey string) string {
	return "standard-protocol-stage-retry:" + strings.TrimSpace(idempotencyKey)
}

func (service *RunService) replayStandardProtocolStageRetry(ctx context.Context, command StandardProtocolStageRetryCommand, job store.DurableJob) (StandardProtocolStageRetryReceipt, error) {
	if job.CommandType != "stage_attempt.execute" || job.EntityType != "stage_attempt" || job.RunID != command.RunID || job.StageAttemptID == "" || job.EntityID != job.StageAttemptID {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("%w: standard protocol retry key", store.ErrIdempotencyConflict)
	}
	retry, err := service.core.store.GetStageAttempt(ctx, job.StageAttemptID)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	if retry == nil || retry.RetryOfStageAttemptID != command.SourceStageAttemptID {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("%w: standard protocol retry source", store.ErrIdempotencyConflict)
	}
	source, err := service.core.store.GetStageAttempt(ctx, retry.RetryOfStageAttemptID)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	run, err := service.core.store.GetWorkflowRun(ctx, job.RunID)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	if source == nil || run == nil {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("%w: standard protocol retry durable lineage", ErrLifecycleNotFound)
	}
	runAttempts, err := service.core.store.ListRunAttempts(ctx, run.ID)
	if err != nil {
		return StandardProtocolStageRetryReceipt{}, err
	}
	var retryRunAttempt store.RunAttempt
	for index := len(runAttempts) - 1; index >= 0; index-- {
		if runAttempts[index].ResumeFrom == "stage_attempt:"+source.ID {
			retryRunAttempt = runAttempts[index]
			break
		}
	}
	if retryRunAttempt.ID == "" {
		return StandardProtocolStageRetryReceipt{}, fmt.Errorf("%w: standard protocol retry run attempt", store.ErrImmutable)
	}
	return StandardProtocolStageRetryReceipt{Run: *run, Source: *source, Retry: *retry, RunAttempt: retryRunAttempt, Job: job, Replayed: true}, nil
}

func standardProtocolStageRetryReceipt(commit store.StageProtocolRetryCommit) StandardProtocolStageRetryReceipt {
	return StandardProtocolStageRetryReceipt{
		Run: commit.Run, Source: commit.Source, Retry: commit.Retry, RunAttempt: commit.RunAttempt, Job: commit.Job, Replayed: commit.Replayed,
	}
}
